"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

MAX_VALUE = 4000000


def get_fibonacci():
    x, y = 0, 1
    while True:
        x, y = y, x + y
        if y >= MAX_VALUE:
            return
        yield y


print(sum(x for x in get_fibonacci() if x % 2 == 0))
